### ISSUE TITLE
Constraints on redistribution? 

### ISSUE THREAD

**Issue by traversaro** [molysgaard/leopard#1]
Hello @molysgaard, thanks a lot for working and making available this project! I still need to test it, but before hand I wanted to ask: there are any constraint on the redistribution of leopard library? I mean, if I ship my software that includes `libleopard.so`, is that allowed or not? What condition I need to comply to do to so? 

Thanks a lot in advance for the reply!

**Comment by molysgaard** [comment]
@traversaro First of all. Thank you for reaching out and showing interest.

I see you are in the robotics field. Maybe you will be pleased to know that my original motivation for starting the development of Leopard back in 2019 was coming from a wish to have fast, nonlinear, smooth, constrained optimization solvers for control systems design.

I would be very happy for Leopard to be used in any setting, academic, commercial, hobbyist, or professional.

In general, I want Leopard to be used.
There are only two constraints I can think of that I think could make sense to impose.
1. There should be some attribution notice in the software linking to Leopard acknowledging that it is using Leopard (C) Morten Lysgaard. If Leopard goes into a physical product, the documentation and software following the product should contain the attribution.
2. You should not modify the headers or dynamic library

What do you think about these terms?

**Comment by traversaro** [comment]
Sure, they seem pretty reasonable terms, thanks!

**Comment by traversaro** [comment]
Sure, they seem pretty reasonable terms, thanks!

**Comment by traversaro** [comment]
I am going to close the issue as you replied to my question, thanks!

**Comment by molysgaard** [comment]
All well. Please give a hint if you end up using Leopard somewhere, it would be interesting to hear about it, to guide future improvements of the library. There is a ton of low-hanging fruit with respect to performance, I just need some concrete use cases to prioritize what should be picked first.

Wish you a nice day.
